"""add is_archived to documents

Revision ID: 3c2a89565961
Revises: 52e0af935ad6
Create Date: 2026-07-13 13:49:34.262932

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c2a89565961"
down_revision: str | Sequence[str] | None = "52e0af935ad6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # document_versions already exists on this DB from before Alembic tracked it —
    # commented out for local recovery only, restore before committing
    # op.create_table('document_versions',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('document_id', sa.Integer(), nullable=False),
    # sa.Column('version_number', sa.Integer(), nullable=False),
    # sa.Column('file_name', sa.String(length=255), nullable=False),
    # sa.Column('storage_url', sa.String(length=2048), nullable=False),
    # sa.Column('content', sa.Text(), nullable=False),
    # sa.Column('job_snapshot', sa.Text(), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    # sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_archived", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table("jobs", schema=None) as batch_op:
    # batch_op.add_column(
    #    sa.Column("notes_updated_at", sa.DATETIME(), nullable=False)
    # )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_column("is_archived")

    # op.drop_table("document_versions")
    # ### end Alembic commands ###
