"""add prep notes to jobs

Revision ID: 4d6861fe9d24
Revises: 52e0af935ad6
Create Date: 2026-07-13 01:02:37.812533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6861fe9d24'
down_revision: Union[str, Sequence[str], None] = '52e0af935ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prep_notes', sa.Text(), nullable=True))
        batch_op.alter_column('notes_updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('interview_notes')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_notes', sa.TEXT(), nullable=True))
        batch_op.alter_column('notes_updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('prep_notes')

    # ### end Alembic commands ###
