"""Added document requests and posts

Revision ID: 555277ce079d
Revises: 0002
Create Date: 2026-07-12 13:22:20.349695

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "555277ce079d"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
