"""add is_archived to documents

Revision ID: c0e0dd3071dd
Revises: 3c2a89565961
Create Date: 2026-07-13 14:13:08.958285

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c0e0dd3071dd"
down_revision: str | Sequence[str] | None = "3c2a89565961"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
