"""Updating documents

Revision ID: f17d94b34263
Revises: 555277ce079d
Create Date: 2026-07-12 14:11:08.562773

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f17d94b34263"
down_revision: str | Sequence[str] | None = "555277ce079d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
